
GET http://localhost:8080/api/trabzon/ortahisar HTTP/1.1

###
POST http://localhost:8080/api/trabzon/ortahisar HTTP/1.1
Content-Type: application/json

{
   
    "name": "invoker4",
    "foto": "none",
    "mainlocation": "Trabzon",
    "bazaarlocation": "Trabzon/Ortahisar",
    "bazaarname": "Kalkınma_Pazari,Konaklar_Pazari",
    "crops": "Elma,Armut,Karpuz,Visne",
    "phone": "055423321451",
    "days": "146"
  }

###
POST http://localhost:3000/api/CREATEUSER HTTP/1.1
Content-type: application/json

{
    "name": "invoker",
    "phone": "none",
    "city": "TRABZON",
    "country": "SANA",
    "explain": "SİTE ADMİNİ"
}

###
GET http://localhost:3000/api/TRABZON/SANA HTTP/1.1

###
GET https://beyazhoroz.herokuapp.com/api/TRABZON/SANA
###

POST https://beyazhoroz.herokuapp.com/api/CREATEUSER
Content-type: application/json

{
    "name": "FURKAN",
    "phone": "none",
    "city": "KASTAMONU",
    "country": "MERKEZ",
    "explain": "SİTE ADMİNİ"
}

###

POST https://beyazhoroz.herokuapp.com/api/CREATELOCATION
Content-type: application/json

{
    "name": "ahmet",
    "information": "sarımsakcıııı alım yapılır. 05313312419",
    "phone": "05313312419",
    "enlem": "43.000940",
    "boylam": "38.210284",
    "initdate": "none",
    "type":"alici"
}
###
GET http://localhost:3000/api/TAVSIYE/RİZE/ HTTP/1.1

###
 GET http://localhost:3000/api/TAVSIYE/ADANA/ HTTP/1.1

 ###



# app.Get("/api/TAVSIYE/:sehir", func(c *fiber.Ctx) error {
		# Id:          primitive.NewObjectID(),
		# Name:        location.Name,
		# Information: location.Information,
		# Phone:       location.Phone,
		# Enlem:       location.Enlem,
		# Boylam:      location.Boylam,

# type Satici struct {
# 	Id             string
# 	Name           string `json:"name"`
# 	Foto           string `json:"foto"`
# 	MainLocation   string `json:"mainlocation"`
# 	BazaarLocation string `json:"bazaarlocation"`
# 	BazaarName     string `json:"bazaarname"`
# 	Crops          string `json:"crops"`
# 	Phone          string `json:"phone"`
# 	Days           string `json:"days"`
# }