version: '1'

services:
  db:
    image: postgres:10.20
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: root
      POSTGRES_DB: authServer
    ports:
     - "5432:5432"